# Site settings
remote_theme: "mmistakes/so-simple-theme"
logo: "/images/icon.png"
locale: "en-us"
title: "KU Leuven Audio Engineering Lab"
description: "Toon van Waterschoot"
mathjax: true
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

# Liquid
liquid:
  error_mode: strict

# Build settings
# permalink: /:categories/:title/
markdown: kramdown
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Search
search_full_content: false

# Taxonomy pages
category_archive_path: "/team/#"
tag_archive_path: "/tags/#"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Collections
collections:
  team:
    output: true
    permalink: /:collection/:path/
  topics:
    output: true
    permalink: /:collection/:path/

# Front Matter Defaults
defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: true
      share: true
  # Team defaults
  - scope:
      path: "_team"
      type: team
    values:
      layout: post
      comments: false
      share: false
  # Topics defaults
  - scope:
      path: "_topics"
      type: topics
    values:
      layout: post_without_date
      comments: false
      share: true

# Site Author
author:
  name: Toon van Waterschoot
  picture: /images/toon_circle.png
  email: toon.vanwaterschoot@esat.kuleuven.be
  twitter: ToonvW
  links:
    - title: Email
      url: mailto:toon.vanwaterschoot@esat.kuleuven.be
      icon: fas fa-at    
    - title: Twitter
      url: https://twitter.com/ToonvW
      icon: fab fa-twitter-square
    - title: LinkedIn
      url: https://linkedin.com/in/toonvanwaterschoot
      icon: fab fa-linkedin
    - title: GitHub
      url: https://github.com/tvanwate
      icon: fab fa-github-square
